spring:
  redis:
    host: 148.70.5.68
    port: 6379
    password:
    database: 0
    pool:
      max-active: 20  # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接

db:
  ds:
    main:
      name: test2
      jdbc-url: jdbc:mysql://127.0.0.1:3306/bootDemo
      url: jdbc:mysql://127.0.0.1:3306/bootDemo
      username: root
      password: root
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
    db1:
      name: test
      url: jdbc:mysql://127.0.0.1:3306/zlb_test1
      jdbc-url: jdbc:mysql://127.0.0.1:3306/zlb_test1
      username: root
      password: root
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
    db2:
      name: test2
      jdbc-url: jdbc:mysql://127.0.0.1:3306/zlb_test2
      url: jdbc:mysql://127.0.0.1:3306/zlb_test2
      username: root
      password: root
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver